// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmktWFGk7tYGcLlpyMe8hGZdyNmCl7o9k',
    appId: '1:460243582134:web:daa7cd29d7d936fc56fa17',
    messagingSenderId: '460243582134',
    projectId: 'blood-donation-app-8d90d',
    authDomain: 'blood-donation-app-8d90d.firebaseapp.com',
    storageBucket: 'blood-donation-app-8d90d.firebasestorage.app',
    measurementId: 'G-N9JRFNW7V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxh0Qft3RKUKeNSVYjJhAW1vQ1LP04q9I',
    appId: '1:460243582134:android:180bc85fe02e87a856fa17',
    messagingSenderId: '460243582134',
    projectId: 'blood-donation-app-8d90d',
    storageBucket: 'blood-donation-app-8d90d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFfrGp2PZLHqz7SkyeYX1JC1T0kXMo5bk',
    appId: '1:460243582134:ios:d338fe7c5d012ab556fa17',
    messagingSenderId: '460243582134',
    projectId: 'blood-donation-app-8d90d',
    storageBucket: 'blood-donation-app-8d90d.firebasestorage.app',
    iosBundleId: 'com.example.bloodBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFfrGp2PZLHqz7SkyeYX1JC1T0kXMo5bk',
    appId: '1:460243582134:ios:d338fe7c5d012ab556fa17',
    messagingSenderId: '460243582134',
    projectId: 'blood-donation-app-8d90d',
    storageBucket: 'blood-donation-app-8d90d.firebasestorage.app',
    iosBundleId: 'com.example.bloodBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmktWFGk7tYGcLlpyMe8hGZdyNmCl7o9k',
    appId: '1:460243582134:web:5e24971f85f6507056fa17',
    messagingSenderId: '460243582134',
    projectId: 'blood-donation-app-8d90d',
    authDomain: 'blood-donation-app-8d90d.firebaseapp.com',
    storageBucket: 'blood-donation-app-8d90d.firebasestorage.app',
    measurementId: 'G-84LHPBFGB9',
  );
}
